# Generated by Django 4.0.2 on 2022-03-31 09:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Name of Movies', max_length=50, verbose_name='name')),
                ('description', models.CharField(db_index=True, default='Description', max_length=500, verbose_name='description')),
                ('release_type', models.CharField(blank=True, choices=[('Newly Released', 'Newly Released'), ('Coming Soon', 'Coming Soon')], max_length=50, null=True, verbose_name='release_type')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('trailer_link', models.CharField(blank=True, db_index=True, max_length=5000, verbose_name='Trailer Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Updated Time')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
